### ISSUE TITLE
[dglo on 2009-05-11 21:39:22] : daq-io - noisy ABEND

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#1117]
In one case where a run failed to start, all the stringHubs died an extremely noisy death, repeatedly spewing this message to their log files, resulting in 3.5G of log messages:

stringHub icecube.daq.io.SimpleOutputEngine-stringHub-1022-hitOut ERROR [2009-05
-11 02:10:42.665] Channel stringHub#1022:hitOut=STOPPED:0 write failed
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcher.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:57)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
        at sun.nio.ch.IOUtil.write(IOUtil.java:103)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:331)
        at icecube.daq.io.SimpleOutputEngine$SimpleOutputChannel.transmit(SimpleOutputEngine.java:828)
        at icecube.daq.io.SimpleOutputEngine.run(SimpleOutputEngine.java:491)
        at java.lang.Thread.run(Thread.java:810)

**Comment by dglo** [comment]
[dglo on 2014-06-11 18:01:22]
Haven't seen this in several years
