### ISSUE TITLE
[kaeld on 2010-06-07 18:34:32] : ClusterTrigger dies throws NPE again

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#1332]
Lately seen in run 116011 ...

Maybe a bug in ClusterTrigger?  I'm not a trigger expert, but I'm hoping the following will be of assistance to someone.

Here's the stack trace that killed the in-ice trigger:

Exception in thread "HKN1Splicer" java.lang.NullPointerException
	at java.util.TreeMap$AbstractMapIterator.remove(TreeMap.java:5779)
	at icecube.daq.trigger.algorithm.ClusterTrigger.processHitQueue(ClusterTrigger.java:222)
	at icecube.daq.trigger.algorithm.ClusterTrigger.runTrigger(ClusterTrigger.java:169)
	at icecube.daq.trigger.control.TriggerHandler.process(TriggerHandler.java:347)
	at icecube.daq.trigger.control.TriggerManager.execute(TriggerManager.java:151)
	at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:487)
	at java.lang.Thread.run(Thread.java:735)

The initial reference to HKN1Splicer is meaningless ... it just indicates that the trigger logic is still being run as part of the splicer thread, rather than in its own thread.

The code which got a NullPointerException is the "it.remove()" statement in:

   // Remove sites in coherence map less than threshold
   for (Iterator<Integer> it = coherenceMap.values().iterator(); it.hasNext(); )
       if (it.next() < multiplicity) it.remove();

**Comment by dglo** [comment]
[sboeser on 2010-11-08 10:10:22]
Oct 2010: 4 run fails due to this

**Comment by dglo** [comment]
[kaeld on 2011-07-08 12:51:30]
these issues have been lurking for too long causing subconscious burden to their assignee.  Proactively dropping them
