### ISSUE TITLE
[dglo on 2010-12-18 03:27:11] : rpc_component_register exception

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#1514]
Catchall icecube.daq.juggler.component.DAQCompServer-main ERROR [2010-12-18 03:20:36.835] Couldn't announce stringHub [rdoutData,tcalData,moniData,genericCache,snData] [OutConn[moniData=>stringHub#79:moniOut=STOPPED],OutConn[rdoutData=>stringHub#79:dataOut=STOPPED],OutConn[snData=>stringHub#79:supernovaOut=STOPPED],OutConn[stringHit=>stringHub#79:hitOut=STOPPED],OutConn[tcalData=>stringHub#79:tcalOut=STOPPED],InConn[rdoutReq=>stringHub[IDLE,0 chan,0 sent]]]
icecube.daq.juggler.component.DAQCompException: Couldn't announce component
        at icecube.daq.juggler.component.DAQCompServer.sendAnnouncement(DAQCompServer.java:1218)
        at icecube.daq.juggler.component.DAQCompServer.runEverything(DAQCompServer.java:1155)
        at icecube.daq.juggler.component.DAQCompServer.startServing(DAQCompServer.java:1492)
        at icecube.daq.stringhub.Shell.main(Shell.java:35)
Caused by: org.apache.xmlrpc.XmlRpcException: <type 'exceptions.Exception'>:method "rpc_component_register" is not supported

**Comment by dglo** [comment]
[dglo on 2011-01-04 23:09:30]
This is only a problem when Jupiter components are run with a Hobees server, and it's not worth fixing Hobees for this case
