### ISSUE TITLE
[mnewcomb on 2011-03-03 22:41:41] : ExpControlSkel.py raises an expection when run with no arguments

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#1636]
ExpControlSkel.py raises an expection when run with no arguments

Traceback (most recent call last):
  File "/usr/local/pdaq/pDAQ_current/dash/ExpControlSkel.py", line 282, in <module>
    if __name__ == "__main__": main()
  File "/usr/local/pdaq/pDAQ_current/dash/ExpControlSkel.py", line 267, in main
    run.start(duration)
  File "/usr/local/pdaq/pDAQ_current/dash/BaseRun.py", line 199, in start
    self.__mgr.updateDB(self.__runCfg)
  File "/usr/local/pdaq/pDAQ_current/dash/BaseRun.py", line 501, in updateDB
    runCfgPath = os.path.join(self.__configDir, runCfg + ".xml")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by dglo** [comment]
[mnewcomb on 2011-03-03 23:46:16]
svn commit -m "Issue: 4649 expcontrolskel throws an exception if you run it with no runcfg.  Changed baserun to throw a reasonable exception if you instantiate it with no run config and changed the command line of ExpControlSkel so it requires a run config to be specified" 
Sending        BaseRun.py
Sending        ExpControlSkel.py
Transmitting file data ..
Committed revision 12745.

**Comment by dglo** [comment]
[dglo on 2011-06-14 19:51:14]
Jupiter is dead, long live Jupiter2 (at least until Kirala)
