### ISSUE TITLE
[dglo on 2011-11-16 22:31:21] : dash - CnCServerTest is broken after SwitchRun commit

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#1811]
CnCServerTest  fails with an error:

% python CnCServerTest.py -v
testSwitchRun (__main__.TestCnCServer) ... ERROR
Traceback (most recent call last):
  File "CnCServerTest.py", line 556, in tearDown
    self.__logFactory.tearDown()
  File "/Users/dglo/prj/pdaq-switch/dash/DAQMocks.py", line 1590, in tearDown
    l.checkStatus(0)
  File "/Users/dglo/prj/pdaq-switch/dash/DAQMocks.py", line 454, in checkStatus
    self.__checkEmpty()
  File "/Users/dglo/prj/pdaq-switch/dash/DAQMocks.py", line 370, in __checkEmpty
    (len(fixed), self.__name, str(fixed)))
Exception: Didn't receive 1 expected stringHub#1021 log messages: ['EXACT:Switch stringHub#1021 to run#445']

======================================================================
ERROR: testSwitchRun (__main__.TestCnCServer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "CnCServerTest.py", line 903, in testSwitchRun
    self.__runEverything(switchRun=True)
  File "CnCServerTest.py", line 792, in __runEverything
    self.cnc.rpc_runset_switch_run(setId, newNum)
  File "/Users/dglo/prj/pdaq-switch/dash/CnCServer.py", line 1300, in rpc_runset_switch_run
    runSet.switchRun(runNum)
  File "/Users/dglo/prj/pdaq-switch/dash/RunSet.py", line 1921, in switchRun
    (bStr))
RunSetException: Still waiting for ['eventBuilder'] to finish switching

----------------------------------------------------------------------
Ran 1 test in 183.935s

FAILED (errors=1)

**Comment by dglo** [comment]
[dglo on 2011-11-16 22:32:45]
svn commit -m"Issue 5360: Unbreak CnCServerTest" CnCServerTest.py 
Sending        CnCServerTest.py
Transmitting file data .
Committed revision 13406.

**Comment by dglo** [comment]
[dglo on 2012-05-10 15:05:17]
These issues are all in releases
