### ISSUE TITLE
[user18 on 2007-03-12 17:34:36] : Dave_G reports an error in DiskUsage.

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#183]
Begin forwarded message:

> From: Dave Glowacki <dave.glowacki@icecube.wisc.edu>
> Date: March 6, 2007 11:31:37 AM PST
> To: "Wile E. Coyote" <SJPatton@lbl.gov>
> Subject: Minor bug in icecube.icebucket.util.DiskUsage
>
> Hi Simon,
>
> While running the pDAQ unit tests on pub.icecube.wisc.edu, I ran into 
> a minor bug in icecube.icebucket.util.DiskUsage, specifically this bit 
> of code at around line 200:
>
>      while (!complete) {
>          final String line;
>          line = output.readLine();
>          dfResult.reset(line);
>          if (null != line) {
>              if (dfResult.matches()) {
>
> It seems that the code is reading to the end of the file, so 'line'  
> is getting set to null.  When dfResult.reset() is called with a null 
> value, I get:
>
>     java.lang.NullPointerException
>         at java.util.regex.Matcher.getTextLength(Matcher.java:1127)
>         at java.util.regex.Matcher.reset(Matcher.java:284)
>         at java.util.regex.Matcher.reset(Matcher.java:304)
>         at icecube.icebucket.util.DiskUsage.getUsage(DiskUsage.java: 
> 202)
>
> Moving the 'dfResult.reset(line);' inside the 'if (null != line) {'  
> block fixes the problem for me.

------------------------------------------------------------------------
Simon Patton
Lawrence Berkeley Nat. Lab.                          Tel: (510) 486-6883

**Comment by dglo** [comment]
[None on 2007-03-21 15:40:24]
Patch applied to glacier SVN repository revision # 290 on the trunk.

**Comment by dglo** [comment]
[None on 2007-03-22 11:09:23]
Released to Maven repository as 3.0.1.\n\n
