### ISSUE TITLE
[dglo on 2012-02-28 16:28:42] : pdaq-user - exception thrown when initializing pdaq account on new host

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#1852]
pdaq@access% fab -H scube setup deploy
[scube] Executing task 'setup'
[scube] Executing task 'deploy'
[scube] Login password: 
[scube] run: mkdir -pm 0700 /usr/local/pdaq/.ssh

Warning: Updating remote list of authorized SSH key

[scube] put: /tmp/tmpk8CNgznew_keys -> /usr/local/pdaq/.ssh/authorized_keys
[scube] run: chmod 0600 /usr/local/pdaq/.ssh/authorized_keys
Traceback (most recent call last):
  File "/home/pdaq/env/lib/python2.6/site-packages/Fabric-1.2.4-py2.6.egg/fabric/main.py", line 773, in main
    _run_task(task, args, kwargs)
  File "/home/pdaq/env/lib/python2.6/site-packages/Fabric-1.2.4-py2.6.egg/fabric/main.py", line 629, in _run_task
    return task(*args, **kwargs)
  File "/mnt/access/home/pdaq/pDAQ_trunk/pdaq-user/fabfile.py", line 602, in deploy
    _sync_ssh_keys(do_local=do_local)
  File "/mnt/access/home/pdaq/pDAQ_trunk/pdaq-user/fabric_pdaq.py", line 616, in _sync_ssh_keys
    if len(dead_keys) > 0:
UnboundLocalError: local variable 'dead_keys' referenced before assignment
Disconnecting from scube... done.

**Comment by dglo** [comment]
[dglo on 2012-02-28 16:29:40]
svn commit -m"Issue 5528: Add missing 'dead_keys' list for hosts without a .ssh directory" fabric_pdaq.py
Sending        fabric_pdaq.py
Transmitting file data .
Committed revision 13525.

**Comment by dglo** [comment]
[dglo on 2012-05-10 15:05:17]
These issues are all in releases
