### ISSUE TITLE
[ksbeattie on 2007-03-22 13:05:58] : trigger jaxb builds fail when using IBM JVM

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#199]
On spts64-build64 when using the IBM JVM, builds fail in the trigger project:

[INFO] ----------------------------------------------------------------------------
[INFO] Building trigger
[INFO]    task-segment: [clean, package]
[INFO] ----------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] Deleting directory /usr/local/pdaq/pDAQ_trunk/trigger/target
[INFO] Deleting directory /usr/local/pdaq/pDAQ_trunk/trigger/target/classes
[INFO] Deleting directory /usr/local/pdaq/pDAQ_trunk/trigger/target/test-classes
[INFO] [jaxb1:generate {execution: default}]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] com.sun.org.apache.xalan.internal.extensions.ExpressionContext
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NoClassDefFoundError: com.sun.org.apache.xalan.internal.extensions.ExpressionContext
        at java.lang.J9VMInternals.verifyImpl(Native Method)
        at java.lang.J9VMInternals.verify(J9VMInternals.java:59)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:120)
        at com.sun.org.apache.xpath.internal.XPathAPI.eval(XPathAPI.java:221)
        at com.sun.org.apache.xpath.internal.XPathAPI.selectNodeList(XPathAPI.java:165)
        at com.sun.tools.xjc.reader.internalizer.Internalizer.buildTargetNodeMap(Internalizer.java:176)
        at com.sun.tools.xjc.reader.internalizer.Internalizer.buildTargetNodeMap(Internalizer.java:223)
        at com.sun.tools.xjc.reader.internalizer.Internalizer.transform(Internalizer.java:99)
        at com.sun.tools.xjc.reader.internalizer.Internalizer.transform(Internalizer.java:67)
        at com.sun.tools.xjc.reader.internalizer.DOMForest.transform(DOMForest.java:208)
        at com.sun.tools.xjc.GrammarLoader.buildDOMForest(GrammarLoader.java:326)
        at com.sun.tools.xjc.GrammarLoader.loadXMLSchema(GrammarLoader.java:371)
        at com.sun.tools.xjc.GrammarLoader.load(GrammarLoader.java:142)
        at com.sun.tools.xjc.GrammarLoader.load(GrammarLoader.java:91)
        at org.jvnet.jaxb1.maven2.AbstractXJC1Mojo.runXJC(AbstractXJC1Mojo.java:430)
        at org.jvnet.jaxb1.maven2.AbstractXJC1Mojo.executeImp(AbstractXJC1Mojo.java:120)
        at org.jvnet.jaxb1.maven2.XJC1Mojo.execute(XJC1Mojo.java:336)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:615)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------

Steps to Reproduce: Change the pdaq/.bashrc to set JAVA_HOME to the IBM one and then try building:
ksbeattie@spts64-build64[pDAQ_trunk] 19:54:29 (0)$ sudo su - pdaq
pdaq@spts64-build64[~] 19:54:30 (0)$ echo $JAVA_HOME
/usr/lib/jvm/java-1.5.0-ibm.x86_64
pdaq@spts64-build64[~] 19:54:34 (0)$ cd pDAQ_trunk/
pdaq@spts64-build64[pDAQ_trunk] 19:54:37 (0)$ mvn -Dmaven.test.skip=true clean package

Additional Information: This doesn't happen on sps-build64 as pdaq, nor does it happen as ksbeattie@spts64-build64.

**Comment by dglo** [comment]
[dglo on 2012-03-09 14:54:40]
"Resolved" this by eliminating the JAXB code

**Comment by dglo** [comment]
[dglo on 2012-05-10 10:05:17]
These issues are all in releases
