### ISSUE TITLE
[dglo on 2007-03-23 07:56:33] : Component monitoring fails in long runs

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#200]
After around 4.5 hours in run 106306, eventBuilder monitoring started failing with an IllegalArgumentException.  A couple hours later, iceTopTrigger started spitting out the same exception.

> java.lang.IllegalArgumentException
>         at java.lang.reflect.Array.setImpl(Native Method)
>         at java.lang.reflect.Array.set(Array.java:312)
>         at icecube.daq.juggler.mbean.XMLRPCServer.fixArray(XMLRPCServer.java:66)
>         at icecube.daq.juggler.mbean.XMLRPCServer.fixValue(XMLRPCServer.java:88)
>         at icecube.daq.juggler.mbean.XMLRPCServer.fixAttribute(XMLRPCServer.java:78)
>         at icecube.daq.juggler.mbean.XMLRPCServer.getList(XMLRPCServer.java:164)
>         at icecube.daq.juggler.mbean.MBeanHandler.getList(MBeanHandler.java:50)

**Comment by dglo** [comment]
[dglo on 2007-03-23 07:58:27]
Added some diagnostics in icecube.daq.juggler.mbean.XMLRPCServer revision 1083 to help diagnose the problem

**Comment by dglo** [comment]
[dglo on 2007-03-29 14:55:57]
Sending        src/main/java/icecube/daq/juggler/mbean/XMLRPCServer.java
Transmitting file data .
Committed revision 1120.
