### ISSUE TITLE
[dglo on 2013-02-02 16:14:44] : RemoveHubs.py cannot handle <hitspool>

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2119]
RemoveHubs.py sps-IC86-hitspool-15-sec-interval-V219 7
Traceback (most recent call last):
 Â File "/home/pdaq/pDAQ_current/dash/RemoveHubs.py", line 130, in <module>
 Â  Â runCfg = DAQConfigParser.load(runCfgName, configDir)
 Â File "/mnt/access/home/pdaq/pDAQ_Ale_Asylum5/dash/XMLFileCache.py", line 79, in load
 Â  Â raise XMLFileParseError("%s: %s" % (fileName, exc_string()))
XMLFileCache.XMLFileParseError: /home/pdaq/pDAQ_current/config/sps-IC86-hitspool-15-sec-interval-V219.xml: ProcessError("Unknown <hitspool> node under <stringHub>") in __parseSenderOption() (DAQConfig.py:1520) <- parse() (DAQConfig.py:1726) <- load() (XMLFileCache.py:76)

**Comment by dglo** [comment]
[mnewcomb on 2013-05-09 21:37:02]
Fixed as part of 6178
