### ISSUE TITLE
[dglo on 2013-04-24 15:56:26] : StringHub - Hit spooling error at end of run

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2136]
At the end of every run the hit spooling code throws an IndexOutOfBoundsException and kills the thread.

[2013-04-24 09:36:32.891000] Aborting sort thread
java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:459)
        at java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:406)
        at icecube.daq.stringhub.FilesHitSpool.consume(FilesHitSpool.java:121)
        at icecube.daq.bindery.MultiChannelMergeSort.run(MultiChannelMergeSort.java:164)

The root cause is FilesHitSpool.consume() getting a short payload for an unknown reason

**Comment by dglo** [comment]
[kaeld on 2013-04-25 13:26:47]
This is a mystery.  There are NO payloads less than 32 bytes in the StringHub back-end (uses the TestDAQ 32-byte header format).  I've tracked this down to an empty 32-byte payload.  I suspect that what is happening is that the buffer is getting sent to Sender.consume() and then flipped() without the position being moved from zero - this results in a buffer with an empty limit.

**Comment by dglo** [comment]
[kaeld on 2013-05-10 15:07:52]
I modified Sender -r14482 to stop flipping the end of stream marker buffers

**Comment by dglo** [comment]
[dglo on 2014-01-20 21:11:43]
Furthermore has been running for several months
