### ISSUE TITLE
[dglo on 2013-07-17 21:09:13] : DAQTime.py prints a cryptic error if PDAQ_CONFIG is not set

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2179]
[7/17/13 3:21:57 PM] John Kelley:

if $PDAQ_CONFIG is not set and you supply a command-line argument, the error is cryptic:
python DAQTime.py 310145739316384283
Bad date: 310145739316384283
Traceback (most recent call last):
  File "DAQTime.py", line 284, in <module>
    dt = PayloadTime.fromString(arg, True)
  File "DAQTime.py", line 171, in fromString
    raise ValueError("Cannot parse date/time '%s'" % timestr)
ValueError: Cannot parse date/time '310145739316384283'

**Comment by dglo** [comment]
[dglo on 2013-07-17 21:11:16]
svn commit -m"Issue 6604: Improve error reporting when PDAQ_CONFIG is not set or is incorrect" DAQTime.py
Sending        DAQTime.py
Transmitting file data .
Committed revision 14589.

**Comment by dglo** [comment]
[dglo on 2014-01-20 21:10:05]
Furthermore has been running for several months
