### ISSUE TITLE
[jacobsen on 2013-12-16 16:09:20] : MultipleObjectsReturned stacktrace from /moni_rate_history.../ URL

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2234]
See attached Django stacktrace email

**Comment by dglo** [comment]
[jacobsen on 2013-12-16 16:09:33]
Delivered-To: john@mail.npxdesigns.com
Received: by 10.194.103.67 with SMTP id fu3csp72619wjb;
        Fri, 13 Dec 2013 11:29:38 -0800 (PST)
X-Received: by 10.50.79.228 with SMTP id m4mr4631700igx.47.1386962978130;
        Fri, 13 Dec 2013 11:29:38 -0800 (PST)
Return-Path: <liveadmin-bounces@icecube.wisc.edu>
Received: from i3mail.icecube.wisc.edu (i3mail.icecube.wisc.edu. [128.104.255.23])
        by mx.google.com with ESMTP id z5si2963809icp.144.2013.12.13.11.29.37
        for <john@mail.npxdesigns.com>;
        Fri, 13 Dec 2013 11:29:38 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of liveadmin-bounces@icecube.wisc.edu designates 128.104.255.23 as permitted sender) client-ip=128.104.255.23;
Authentication-Results: mx.google.com;
       spf=pass (google.com: best guess record for domain of liveadmin-bounces@icecube.wisc.edu designates 128.104.255.23 as permitted sender) smtp.mail=liveadmin-bounces@icecube.wisc.edu
Received: from localhost (localhost [127.0.0.1])
	by i3mail.icecube.wisc.edu (Postfix) with ESMTP id 80A3F38124
	for <john@mail.npxdesigns.com>; Fri, 13 Dec 2013 13:29:37 -0600 (CST)
X-Virus-Scanned: amavisd-new at icecube.wisc.edu
Received: from i3mail.icecube.wisc.edu ([127.0.0.1])
	by localhost (i3mail.icecube.wisc.edu [127.0.0.1]) (amavisd-new, port 10026)
	with ESMTP id dFFxOrjvT6B5 for <john@mail.npxdesigns.com>;
	Fri, 13 Dec 2013 13:29:36 -0600 (CST)
Received: from i3mail.icecube.wisc.edu (i3mail.icecube.wisc.edu [172.16.224.23])
	by i3mail.icecube.wisc.edu (Postfix) with ESMTP id E4F7738123
	for <john@mail.npxdesigns.com>; Fri, 13 Dec 2013 13:29:36 -0600 (CST)
X-Original-To: liveadmin@icecube.wisc.edu
Delivered-To: liveadmin@icecube.wisc.edu
Received: from localhost (localhost [127.0.0.1])
	by i3mail.icecube.wisc.edu (Postfix) with ESMTP id 603E938123
	for <liveadmin@icecube.wisc.edu>; Fri, 13 Dec 2013 13:29:36 -0600 (CST)
X-Virus-Scanned: amavisd-new at icecube.wisc.edu
Received: from i3mail.icecube.wisc.edu ([127.0.0.1])
	by localhost (i3mail.icecube.wisc.edu [127.0.0.1]) (amavisd-new,
	port 10026)
	with ESMTP id F5DV1AfJq9gd for <liveadmin@icecube.wisc.edu>;
	Fri, 13 Dec 2013 13:29:35 -0600 (CST)
Received: from cygnus.icecube.wisc.edu (cygnus.icecube.wisc.edu
	[172.16.224.59])
	by i3mail.icecube.wisc.edu (Postfix) with ESMTP id B9AD93808F
	for <liveadmin@icecube.wisc.edu>; Fri, 13 Dec 2013 13:29:35 -0600 (CST)
MIME-Version: 1.0
From: root@localhost.icecube.wisc.edu
To: liveadmin@icecube.wisc.edu
Date: Fri, 13 Dec 2013 19:29:35 -0000
Message-ID: <20131213192935.7333.43289@cygnus.icecube.wisc.edu>
Subject: [LIVEADMIN] [Django] ERROR (EXTERNAL IP): Internal Server Error:
 /moni_rate_history/123358/trigger/37/
X-BeenThere: liveadmin@icecube.wisc.edu
X-Mailman-Version: 2.1.12
Precedence: list
List-Id: Mailing list for IceCube Live administrators
	<liveadmin.icecube.wisc.edu>
List-Unsubscribe: <http://lists.icecube.wisc.edu/mailman/options/liveadmin>,
	<mailto:liveadmin-request@icecube.wisc.edu?subject=unsubscribe>
List-Archive: <http://lists.icecube.wisc.edu/pipermail/liveadmin/>
List-Post: <mailto:liveadmin@icecube.wisc.edu>
List-Help: <mailto:liveadmin-request@icecube.wisc.edu?subject=help>
List-Subscribe: <http://lists.icecube.wisc.edu/mailman/listinfo/liveadmin>,
	<mailto:liveadmin-request@icecube.wisc.edu?subject=subscribe>
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Sender: liveadmin-bounces@icecube.wisc.edu
Errors-To: liveadmin-bounces@icecube.wisc.edu

Traceback (most recent call last):

  File "/usr/local/pdaq/env/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/pdaq/env/lib/python2.6/site-packages/live-2.2.2-py2.6.egg/liveview/decorators.py", line 94, in wrapper
    context = view_func(request, *args, **kwargs)

  File "/usr/local/pdaq/env/lib/python2.6/site-packages/live-2.2.2-py2.6.egg/liveview/views.py", line 1050, in moni_rate_history
    trigger_type=rate_id).rate

  File "/usr/local/pdaq/env/lib/python2.6/site-packages/django/db/models/manager.py", line 131, in get
    return self.get_query_set().get(*args, **kwargs)

  File "/usr/local/pdaq/env/lib/python2.6/site-packages/django/db/models/query.py", line 368, in get
    % (self.model._meta.object_name, num, kwargs))

MultipleObjectsReturned: get() returned more than one Trigger -- it returned 2! Lookup parameters were {'r': <Run: 121801>, 'trigger_type': u'37'}


<WSGIRequest
path:/moni_rate_history/123358/trigger/37/,
GET:<QueryDict: {u'configs': [u'sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no01-no02', u'sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no41', u'sps-IC86-bigRing-above-dust-high-smt-V214', u'sps-IC86-remove-Ligyrophobia-and-Springfield-V230_IceTopSOUTH_InIceSOUTH_partition', u'sps-IC86-remove-Ligyrophobia-and-Springfield-iDom-V230', u'sps-IC86-bigRing-above-dust-V213', u'sps-IC86-remove-Ligyrophobia-and-Springfield-V230', u'sps-IC86-remove-Ligyrophobia-and-Springfield-V230_IceTopNORTH_partition', u'sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no40-no49-no57-no59'], u'days': [u'360']}>,
POST:<QueryDict: {}>,
COOKIES:{'__utma': '249866969.1335446245.1386875549.1386875549.1386900853.2',
 '__utmc': '249866969',
 '__utmz': '249866969.1386875549.1.1.utmcsr=facebook.com|utmccn=(referral)|utmcmd=referral|utmcct=/',
 'csrftoken': 'Dss9z3BlRhfmQit07wfHZNghACcDvaAD',
 'i3_authenticated': 'true',
 'sessionid': 'f553b66f1f48aba995518ed6ccef6977'},
META:{'DOCUMENT_ROOT': '/var/www/html',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTPS': '1',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip,deflate,sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,de;q=0.6,fr;q=0.4',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': '__utma=249866969.1335446245.1386875549.1386875549.1386900853.2; __utmc=249866969; __utmz=249866969.1386875549.1.1.utmcsr=facebook.com|utmccn=(referral)|utmcmd=referral|utmcct=/; csrftoken=Dss9z3BlRhfmQit07wfHZNghACcDvaAD; i3_authenticated=true; sessionid=f553b66f1f48aba995518ed6ccef6977',
 'HTTP_HOST': 'live.icecube.wisc.edu',
 'HTTP_REFERER': 'https://live.icecube.wisc.edu/moni_rate_history/123358/trigger/37/?days=180&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no01-no02&configs=sps-IC86-bigRing-above-dust-V213&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no41&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-iDom-V230&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230_IceTopNORTH_partition&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no40-no49-no57-no59&configs=sps-IC86-bigRing-above-dust-high-smt-V214&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230_IceTopSOUTH_InIceSOUTH_partition',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36',
 'PATH_INFO': u'/moni_rate_history/123358/trigger/37/',
 'PATH_TRANSLATED': '/usr/local/pdaq/wsgi/django.wsgi/moni_rate_history/123358/trigger/37/',
 'QUERY_STRING': 'days=360&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no01-no02&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no41&configs=sps-IC86-bigRing-above-dust-high-smt-V214&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230_IceTopSOUTH_InIceSOUTH_partition&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-iDom-V230&configs=sps-IC86-bigRing-above-dust-V213&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230_IceTopNORTH_partition&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no40-no49-no57-no59',
 'REMOTE_ADDR': '129.49.61.206',
 'REMOTE_PORT': '50448',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/moni_rate_history/123358/trigger/37/?days=360&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no01-no02&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no41&configs=sps-IC86-bigRing-above-dust-high-smt-V214&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230_IceTopSOUTH_InIceSOUTH_partition&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-iDom-V230&configs=sps-IC86-bigRing-above-dust-V213&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230_IceTopNORTH_partition&configs=sps-IC86-remove-Ligyrophobia-and-Springfield-V230-no40-no49-no57-no59',
 'SCRIPT_FILENAME': '/usr/local/pdaq/wsgi/django.wsgi',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '172.16.224.59',
 'SERVER_ADMIN': 'root@localhost',
 'SERVER_NAME': 'live.icecube.wisc.edu',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache',
 'SSL_TLS_SNI': 'live.icecube.wisc.edu',
 'mod_wsgi.application_group': 'live.icecube.wisc.edu|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '443',
 'mod_wsgi.process_group': 'live.icecube.wisc.edu',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 2),
 'wsgi.errors': <mod_wsgi.Log object at 0x7ffe7a922970>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7ffe7a86da80>,
 'wsgi.input': <mod_wsgi.Input object at 0x7ffe7a922730>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 1)}>
_______________________________________________
liveadmin mailing list
liveadmin@icecube.wisc.edu
http://lists.icecube.wisc.edu/mailman/listinfo/liveadmin

**Comment by dglo** [comment]
[mfrere on 2014-01-07 16:32:43]
Thanks for posting this. Looks like we got duplicate entries in there. 

At first sight, potential solutions could be:
- quick fix: use filter(...)[0]
- long term~ish fix: remove any unnecessary duplicates and prevent new ones

**Comment by dglo** [comment]
[dglo on 2014-05-28 17:37:08]
This should have been entered as a 'live' issue
