### ISSUE TITLE
[dglo on 2014-10-23 21:22:14] : standard-tests.py is broken

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2369]
jimbraun [2:25 PM] 
I'm not able to run standard-tests.py on SPTS:

jimbraun [2:25 PM]
pdaq@expcont[~] 19:24:19 (1)$ standard-tests.py -q
Traceback (most recent call last):
 File "/usr/local/pdaq/pDAQ_current/dash/standard-tests.py", line 15, in <module>
   run_tests(args)
 File "/usr/local/pdaq/pDAQ_current/dash/StandardTests.py", line 304, in run_tests
   dryRun=args.dryRun)
 File "/usr/local/pdaq/pDAQ_current/dash/liverun.py", line 406, in __init__
   dryRun=dryRun, logfile=logfile)
 File "/usr/local/pdaq/pDAQ_current/dash/BaseRun.py", line 604, in __init__
   self.__dbType = ClusterDescription.getClusterDatabaseType()
 File "/usr/local/pdaq/pDAQ_current/dash/ClusterDescription.py", line 701, in getClusterDatabaseType
   dbname = cls.getLiveDBName()
TypeError: unbound method getLiveDBName() must be called with ClusterDescription instance as first argument (got nothing instead)

**Comment by dglo** [comment]
[dglo on 2014-10-23 21:24:27]
svn commit -m"Issue 7129: ClusterDescription.getLiveDBName() should be a class method" ClusterDescription.py
Sending        ClusterDescription.py
Transmitting file data .
Committed revision 15203.

**Comment by dglo** [comment]
[dglo on 2015-02-02 19:49:48]
Joseph_Schlitz has been running on SPS for several days
