### ISSUE TITLE
[dglo on 2014-10-24 14:40:53] : Bad argument for subprocess in RestartSPTS.py

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2370]
Error non-zero return code ( 255 ) for host: daq06, cmd: sleep 2; ssh daq06 pkill -9 -f stringhub.componentId=60
Results ''
Traceback (most recent call last):
 File "/usr/local/pdaq/pDAQ_current/dash/RestartSPTS.py", line 351, in <module>
   startRuns(numStopless=NUM_STOPLESS_VALUE, verbose=args.verbose)
 File "/usr/local/pdaq/pDAQ_current/dash/RestartSPTS.py", line 312, in startRuns
   rtn = subprocess.call(args)
 File "/usr/lib64/python2.6/subprocess.py", line 478, in call
   p = Popen(*popenargs, **kwargs)
 File "/usr/lib64/python2.6/subprocess.py", line 639, in __init__
   errread, errwrite)
 File "/usr/lib64/python2.6/subprocess.py", line 1228, in _execute_child
   raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by dglo** [comment]
[dglo on 2014-10-24 14:43:21]
svn commit -m"Issue 7130: Don't try to pass None as an argument" RestartSPTS.py
Sending        RestartSPTS.py
Transmitting file data .
Committed revision 15204.

**Comment by dglo** [comment]
[dglo on 2015-02-02 19:49:48]
Joseph_Schlitz has been running on SPS for several days
