### ISSUE TITLE
[tbendfelt on 2014-11-26 21:44:38] : AbstractRapCal.java - Guard against unconfigured monitor subsystem

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2397]
When running rapcal from Omicron, an error from the dor blows out the stack with a NullPointerException because the LiveTCalMoni object has not been configured:

549003 [01B] WARN  icecube.daq.rapcal.AbstractRAPCal  - Wild TCAL - cable len: 1.5631143882460433E-5 avg. cable len: 1.5620871800259563E-5
549003 [01B] ERROR icecube.daq.domapp.DataCollector  - Intercepted error in DataCollector runcore
java.lang.NullPointerException
	at icecube.daq.rapcal.AbstractRAPCal$Isochron.<init>(AbstractRAPCal.java:54)
	at icecube.daq.rapcal.AbstractRAPCal$Isochron.<init>(AbstractRAPCal.java:42)
	at icecube.daq.rapcal.AbstractRAPCal.update(AbstractRAPCal.java:184)
	at icecube.daq.domapp.DataCollector.execRapCal(DataCollector.java:794)
	at icecube.daq.domapp.DataCollector.runcore_interval(DataCollector.java:1363)
	at icecube.daq.domapp.DataCollector.runcore_universal(DataCollector.java:1044)
	at icecube.daq.domapp.DataCollector.run(DataCollector.java:857)

We should add a guard and route error to log to keep Omicron work-alike to StringHub.

**Comment by dglo** [comment]
[tbendfelt on 2015-08-25 21:05:24]
Fixed as a side effect of 7445 which added a null guard to error moni reporting.

**Comment by dglo** [comment]
[dglo on 2016-03-22 16:06:15]
New_Glarus is almost here!
