### ISSUE TITLE
[tbendfelt on 2015-04-27 16:19:46] : LogSorter.py - Fix the TCAL noise screening broken by new data collector.

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2504]
Issue 7181 changed error message signature for TCAL exceptions in data collector.  

Prior to Lake Louie the message is:

stringHub#38 icecube.daq.domapp.DataCollector-60B WARN [2015-04-23 04:42:16.294] Got IO exception
java.io.IOException: TCAL read failed.
	at icecube.daq.dor.Driver.readTCAL(Driver.java:236)
	at icecube.daq.domapp.DataCollector.execRapCal(DataCollector.java:1445)
	at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:1752)
	at icecube.daq.domapp.DataCollector.launch_runcore(DataCollector.java:1695)
	at icecube.daq.domapp.DataCollector.run(DataCollector.java:1514)

After Lake Louie the message is:

   stringHub#38 icecube.daq.domapp.NewDataCollector-60A ERROR [2015-04-25 09:51:01.4160000000] Ignoring tcal error
icecube.daq.domapp.dataacquisition.AcquisitionError: IO Error performing a tcal on [60A]
	at icecube.daq.domapp.dataacquisition.DataAcquisition.doTCAL(DataAcquisition.java:715)
	at icecube.daq.domapp.NewDataCollector.execRapCal(NewDataCollector.java:287)
	at icecube.daq.domapp.NewDataCollector.runcore(NewDataCollector.java:450)
	at icecube.daq.domapp.NewDataCollector.launch_runcore(NewDataCollector.java:387)
	at icecube.daq.domapp.NewDataCollector.run(NewDataCollector.java:326)
Caused by: java.io.IOException: TCAL read failed.
	at icecube.daq.dor.Driver.readTCAL(Driver.java:236)
	at icecube.daq.domapp.dataacquisition.DataAcquisition.doTCAL(DataAcquisition.java:700)

**Comment by dglo** [comment]
[tbendfelt on 2015-04-27 17:18:56]
svn log -v -r15550
------------------------------------------------------------------------
r15550 | bendfelt | 2015-04-27 12:17:00 -0500 (Mon, 27 Apr 2015) | 1 line
Changed paths:
   M /projects/dash/trunk/LogSorter.py

Issue 7344: Make TCAL error filtering work-alike with prior StringHub releases.
------------------------------------------------------------------------
