### ISSUE TITLE
[dglo on 2015-06-16 17:32:34] : Wait for builders to finish switching before fetching run data

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2514]
On SPTS I saw at least one switched run which contained this error:

secondaryBuilders org.apache.xmlrpc.server.XmlRpcErrorLogger-XML-RPC-0 ERROR [2015-06-16 11:40:23.623] Failed to invoke meth
od getRunData in class icecube.daq.juggler.component.DAQCompServer: No final counts found for run 130884; state is switching
org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method getRunData in class icecube.daq.juggler.componen
t.DAQCompServer: No final counts found for run 130884; state is switching
        at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:129)
        at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
        at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
        at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
        at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
        at org.apache.xmlrpc.webserver.Connection.run(Connection.java:208)
        at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:68)
Caused by: icecube.daq.juggler.component.DAQCompException: No final counts found for run 130884; state is switching
        at icecube.daq.secBuilder.SBComponent.getRunData(SBComponent.java:597)
        at icecube.daq.juggler.component.DAQCompServer.getRunData(DAQCompServer.java:829)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:622)
        at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)

**Comment by dglo** [comment]
[dglo on 2015-08-21 15:28:27]
See also: https://live.icecube.wisc.edu/run/126755/

**Comment by dglo** [comment]
[dglo on 2015-08-28 23:04:06]
svn commit -m"Issue 7401: Collapse a bunch of duplicate cluster operation code into a ComponentOperationGroup.runSimple() call"
Sending        CompOp.py
Sending        DAQServerTest.py
Sending        RunSet.py
Sending        RunSetTest.py
Transmitting file data ....done
Committing transaction...
Committed revision 15713.

svn commit -m"Issue 7401: Switch builders before triggers before hubs"
Sending        RunSet.py
Transmitting file data .done
Committing transaction...
Committed revision 15714.

**Comment by dglo** [comment]
[dglo on 2015-09-02 18:49:28]
svn commit -m"Issue 7401: Lose dead code, improve log message about missing components" dash/RunSet.py
Sending        dash/RunSet.py
Transmitting file data .
Committed revision 15727.

**Comment by dglo** [comment]
[dglo on 2015-09-04 20:34:08]
svn commit -m"Issue 7401: Unbreak unit test" RunSetTest.py
Sending        RunSetTest.py
Transmitting file data .done
Committing transaction...
Committed revision 15745.

**Comment by dglo** [comment]
[dglo on 2016-03-22 16:05:54]
New_Glarus is almost here!
