### ISSUE TITLE
[dglo on 2017-02-08 17:54:19] : stdtest dies while trying to summarize nonexistent run

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2783]
While John was doing a stdtest run on SPTS, he saw the following error:

 Started run 167798 (900 secs) replay-125659-local
Traceback (most recent call last):
  File "/usr/local/pdaq/pDAQ_current/dash/BaseRun.py", line 911, in run
    run.wait()
  File "/usr/local/pdaq/pDAQ_current/dash/BaseRun.py", line 609, in wait
    self.__mgr.summarize(self.__run_num)
  File "/usr/local/pdaq/pDAQ_current/dash/BaseRun.py", line 971, in summarize
    summary = self.cncConnection().rpc_run_summary(runNum)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1253, in request
    return self._parse_response(h.getfile(), sock)
  File "/usr/lib64/python2.6/xmlrpclib.py", line 1392, in _parse_response
    return u.close()
  File "/usr/lib64/python2.6/xmlrpclib.py", line 838, in close
    raise Fault(**self._stack[0])
Fault: <Fault 1: "<class 'RunSet.RunSetException'>:No run directory found for run 167798">
!! Cannot summarize run 167798: Fault("<Fault 1: "<class 'RunSet.RunSetException'>:No run directory found for run 167798">") in close() (xmlrpclib.py:838) <- _parse_response() (xmlrpclib.py:1392) <- request() (xmlrpclib.py:1253) <- __request() (xmlrpclib.py:1489) <- __call__() (xmlrpclib.py:1199) <- summarize() (BaseRun.py:971) <- finish() (BaseRun.py:450)

Additional Information: Dave found the original cause of the problem in `~/.i3live.log`:

pdaq(log:str) 4 [2017-02-08 16:11:57.833691] Loading run configuration "replay-125659-local"
pdaq(log:str) 4 [2017-02-08 16:11:57.845952] Loaded run configuration "replay-125659-local"
pdaq(log:str) 4 [2017-02-08 16:11:57.852460] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:02.857883] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:07.863523] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:12.869089] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:17.874595] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:22.880023] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:27.885608] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:32.891209] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:37.896818] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:42.902479] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:47.908033] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:52.913593] Waiting for replayHub#27
pdaq(log:str) 4 [2017-02-08 16:12:58.224778] Cycling components replayHub#27
livecontrol(log:str) 1 [2017-02-08 16:13:01.893804] Found one or more components in error state (pdaq localhost:6659 (synchronous): ERROR)!

**Comment by dglo** [comment]
[dglo on 2017-02-08 19:12:56]
svn commit -m"Issue 8058: Don't let exceptions from summarize() take down the run monitor" BaseRun.py
Sending        BaseRun.py
Transmitting file data .done
Committing transaction...
Committed revision 16438.
