### ISSUE TITLE
[dglo on 2007-05-07 15:59:32] : eventBuilder - every other run fails

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#282]
Every other run fails with
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]Exception in thread "EventBuilderBackEnd" java.lang.IndexOutOfBoundsException
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at java.nio.Buffer.checkIndex(Buffer.java:459)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:355)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at icecube.daq.payload.impl.PayloadEnvelope.loadData(PayloadEnvelope.java:89)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at icecube.daq.payload.splicer.Payload.loadEnvelope(Payload.java:150)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at icecube.daq.payload.splicer.Payload.loadSpliceablePayload(Payload.java:374)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at icecube.daq.payload.splicer.Payload.deepCopy(Payload.java:479)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at icecube.daq.payload.splicer.CompositePayloadFactory.deepCopyPayloadVector(CompositePayloadFactory.java:66)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at icecube.daq.eventbuilder.impl.EventPayload_v2Factory.createPayload(EventPayload_v2Factory.java:92)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at icecube.daq.eventBuilder.backend.EventBuilderBackEnd.makeDataPayload(EventBuilderBackEnd.java:644)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at icecube.daq.reqFiller.RequestFiller$BackEndThread.run(RequestFiller.java:1141)
eventBuilder STDERR-EventBuilderBackEnd ERROR [Mon May 07 05:14:51 UTC 2007]	at java.lang.Thread.run(Thread.java:799)

**Comment by dglo** [comment]
[dglo on 2007-05-09 17:20:23]
There is debugging code running at Pole

**Comment by dglo** [comment]
[kaeld on 2007-11-06 16:29:21]
I examined a short run 108744 from 2007-06-18 to examine event rate of (4000,0) (In-Ice SMT) triggers.  The resulting plot of the 90 second run is shown in the attached file 'rates.png'.  The rate is variable - I assume because of the massive errors about out-of-order payloads.
