### ISSUE TITLE
[dglo on 2018-05-14 21:35:17] : Detector hung after run 131029 failure

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2928]
Run 131029 failed with this exception:

[2018-05-11 03:22:59.0478460000] Cannot start runset#3: Traceback (most recent call last):
  File "/usr/local/pdaq/pDAQ_current/dash/CnCServer.py", line 1432, in startRun
    log_dir=log_dir, quiet=self.__quiet)
  File "/usr/local/pdaq/pDAQ_current/dash/RunSet.py", line 2838, in start_run
    self.__start_components(quiet)
  File "/usr/local/pdaq/pDAQ_current/dash/RunSet.py", line 1925, in __start_components
    self.__id)
RunSetException: Could not get runset#3 latest first time

After this error, Live could not get pDAQ to recover so the detector hung for 5 minutes

**Comment by dglo** [comment]
[dglo on 2018-05-15 18:12:40]
svn commit -m"Issue 8429: Add a few more status checks to RunSetTest.__runTests()" RunSetTest.py 
Sending        RunSetTest.py
Transmitting file data .done
Committing transaction...
Committed revision 17013.

svn commit -m"Issue 8429: Rework startup code that caused detector to hang"
Sending        CnCServer.py
Sending        DAQLive.py
Sending        DAQMocks.py
Sending        RunSet.py
Sending        RunSetTest.py
Transmitting file data .....
Committed revision 17015.
