### ISSUE TITLE
[dglo on 2019-04-18 21:25:07] : XML-RPC error for run 132450

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#2990]
eventBuilder org.apache.xmlrpc.server.XmlRpcErrorLogger-XML-RPC-0 ERROR [2019-04-18 01:16:20.1010000000] java.lang.NullPointerException
java.lang.NullPointerException
   at org.apache.xmlrpc.webserver.XmlRpcStatisticsServer.execute(XmlRpcStatisticsServer.java:87)
   at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
   at org.apache.xmlrpc.webserver.Connection.run(Connection.java:208)
   at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:68)
eventBuilder - - [2019-04-18 01:16:20.1671630000] Fault("<Fault 0: ''>") in close() (xmlrpclib.py:838) <- _parse_response() (xmlrpclib.py:1392) <- request() (xmlrpclib.py:1253) <- __request() (xmlrpclib.py:1489) <- __call__() (xmlrpclib.py:1199) <- getRunData() (DAQClient.py:451)

**Comment by dglo** [comment]
[dglo on 2019-04-18 21:26:36]
svn commit -m"Issue 8645: Fix a (possible?) race condition in XMLRPCServer; disable RPC-timing unless TIME_RPC_CALL is set to true"
Sending        src/main/java/icecube/daq/juggler/component/DAQCompServer.java
Sending        src/main/java/icecube/daq/juggler/mbean/XMLRPCServer.java
Sending        src/main/java/org/apache/xmlrpc/webserver/DAQWebServer.java
Sending        src/main/java/org/apache/xmlrpc/webserver/XmlRpcStatisticsServer.java
Sending        src/test/java/icecube/daq/juggler/mbean/MBeanAgentTest.java
Transmitting file data .....
Committed revision 17346.

**Comment by dglo** [comment]
[dglo on 2019-05-29 16:57:11]
svn commit -m"Issue 8645: Fix problems with rev 17346" .
Sending        src/main/java/icecube/daq/juggler/component/DAQCompServer.java
Sending        src/main/java/icecube/daq/juggler/mbean/XMLRPCServer.java
Sending        src/test/java/icecube/daq/juggler/mbean/MBeanAgentTest.java
Transmitting file data ...
Committed revision 17395.

**Comment by dglo** [comment]
[dglo on 2020-04-01 12:25:51]
Urban_Harvest is done
