### ISSUE TITLE
[jacobsen on 2007-07-18 15:29:51] : dash - RunSummary.py stops due to files which mysteriously go missing

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#436]
Seems that .snippet files are sometimes missing - RunSummary.py should survive this at the very least; the underlying cause should also be addressed.

Steps to Reproduce: E.g. [jacobsen@cobalt3 runs]$ rm ../.done && nice /home/jacobsen/icecube/work/pdaq_trunk/dash/RunSummary.py -o /net/usr/pdaq/daq-reports/sps -s /data/exp/IceCube/2007/internal-system/SouthPole -r -l -x 10
/net/usr/pdaq/daq-reports/sps/runs
Traceback (most recent call last):
  File "/home/jacobsen/icecube/work/pdaq_trunk/dash/RunSummary.py", line 552, in ?
    if __name__ == "__main__": main()
  File "/home/jacobsen/icecube/work/pdaq_trunk/dash/RunSummary.py", line 541, in main
    print >>allSummaryFile, getSnippetHtml(snippetFile)
  File "/home/jacobsen/icecube/work/pdaq_trunk/dash/RunSummary.py", line 271, in getSnippetHtml
    return open(snippetFile).read()
IOError: [Errno 2] No such file or directory: '/net/usr/pdaq/daq-reports/sps/runs/107031_20070426_073352_000007/.snippet'

**Comment by dglo** [comment]
[jacobsen on 2007-07-18 15:42:58]
Sending        RunSummary.py
Transmitting file data .
Committed revision 1780.

**Comment by dglo** [comment]
[jacobsen on 2007-08-14 15:45:57]
This problem seems to have disappeared for the moment.

**Comment by dglo** [comment]
[jacobsen on 2007-09-20 21:46:21]
Sending        RunSummary.py
Transmitting file data .
Committed revision 2065.
