### ISSUE TITLE
[krasberg on 2007-10-01 15:54:39] : Firmware fuse trips and DOMs rebooting to configboot occasionally - associated with obscure comm error

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#552]
No associated GitHub commit

**Comment by dglo** [comment]
[jacobsen on 2007-10-01 18:42:33]
On Oct 1, 2007, at 4:25 PM, Kael Hanson wrote:

Hi John,
actually 2 - 1 is do you have any idea why a current trip in a dom would be preceeded by return value of 67 in status byte to a GET_DATA message?

Kael -- This is VERY strange, as there is no way for this message to fail in the domapp code!!!  Either you have data or you don't, neither is an error condition.

      /*  check for available data */
    case DATA_ACC_GET_DATA:
      // try to fill in message buffer with waveform data
      tmpInt = fillMsgWithData(data, MAXDATA_VALUE, dataFormat, compMode);
      Message_setDataLen(M, tmpInt);
      Message_setStatus(M, SUCCESS);
      break;

You have multiple messages in flight, no?  Any chance of dumping the actual received message type and subtype when this happens?  Maybe this is the response of a different message (moni, etc. -- actually if it were moni that would help explain why this happens in 429, since all that new moni stuff came in then...).

John\n\n

**Comment by dglo** [comment]
[jacobsen on 2007-10-01 18:50:19]
From: 	  john@mail.npxdesigns.com
	Subject: 	New Topic added to South Pole Operations ChangeLog on DocuShare ( http://docushare.icecube.wisc.edu/ )
	Date: 	October 1, 2007 6:38:23 PM CDT
	To: 	  john@mail.npxdesigns.com


The following Topic was added by Mark Krasberg on Monday, October 1, 2007 06:38:22 PM CDT

	URL : http://docushare.icecube.wisc.edu/dsweb/View/Bulletin-1142?init=true
	Title : power cycled 3 wire pairs
	Abstract : 
	Description : 
there were three problem wire pairs
<br>
hub 58 card 5 pair 3
<br>
hub 73 card 1 pair 0
<br>
hub 74 card 2 pair 3

<br>
<br>
stopped pDAQ, ran pCycle on these three wire pairs, restored DOMs and started up pDAQ run 109412.
<br>
All expected DOMs appear to be communicating, and no firmware fuses are currently blown.

	revision_comments : 
	Appears In : South Pole Operations ChangeLog
	Owner : krasberg
	Handle : Bulletin-1142
	Create Date : Monday, October 1, 2007 06:38:22 PM CDT


This notification was generated by Subscription-185
	 http://docushare.icecube.wisc.edu/dsweb/Services/Subscription-185

**Comment by dglo** [comment]
[jacobsen on 2007-10-01 18:50:38]
Guys - fyi - I reviewed the hardware timeouts with Mark and it appears (if we are talking about the same thing) that they are one and the same with the resurgence of the dropped DOM problem.  The DOR fuse trips are very odd.
Kael

**Comment by dglo** [comment]
[jacobsen on 2007-10-01 19:01:34]
From: 	  mark.krasberg@icecube.wisc.edu
	Subject: 	dor firmware fuse trip for hub 58
	Date: 	October 1, 2007 4:49:10 PM CDT
	To: 	  kaeld@icecube.wisc.edu
	Cc: 	  john@johnj.com, sulanke@ifh.de


sps-ichub58 : Card 5 pair 3 pwr check: plugged(ok) 
current(ok,ERR_CURRENT_ABOVE_LIMITS) voltage(ok,ok)


from /var/log/messages:

DOMs started RETXing at 1:24:48
hardware timeout occured at 1:24:54



the pDAQ logs kael found look like:

stringHub - - [2007-10-01 01:00:25.405757] Start of log at 10.1.2.12:9016
stringHub STDERR-53A ERROR [2007-10-01 01:24:53.887] GET_DATA - status: 67
stringHub STDERR-53A ERROR [2007-10-01 01:24:53.895] 	at icecube.daq.domapp.DOMApp.getData(DOMApp.java:161)
stringHub STDERR-53A ERROR [2007-10-01 01:24:53.896] 	at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:863)
stringHub STDERR-53A ERROR [2007-10-01 01:24:53.896] 	at icecube.daq.domapp.DataCollector.run(DataCollector.java:681)
stringHub icecube.daq.domapp.DataCollector-53A ERROR [2007-10-01 01:24:53.896] Intercepted error in DataCollector runcore: GET_DATA - status: 67
stringHub STDERR-53B ERROR [2007-10-01 01:24:54.546] GET_DATA - status: 67
stringHub STDERR-53B ERROR [2007-10-01 01:24:54.547] 	at icecube.daq.domapp.DOMApp.getData(DOMApp.java:161)
stringHub STDERR-53B ERROR [2007-10-01 01:24:54.547] 	at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:863)
stringHub STDERR-53B ERROR [2007-10-01 01:24:54.547] 	at icecube.daq.domapp.DataCollector.run(DataCollector.java:681)
stringHub icecube.daq.domapp.DataCollector-53B ERROR [2007-10-01 01:24:54.547] Intercepted error in DataCollector runcore: GET_DATA - status: 67


the fpga registers look like:

sps-ichub58 testdaq /mnt/data/testdaq/ cat /proc/driver/domhub/card5/fpga
FPGA registers:
CTRL  0x6800300f
GSTAT 0x00007dca
DSTAT 0x008050ff
TTSIC 0x0000ffff
RTSIC 0x3f0000ff
INTEN 0x00010200
DOMS  0x3f0000ff
MRAR  0x375ab000
MRTC  0x01000000
MWAR  0x375adc04
MWTC  0x01000000
CURL  0xe19e8c14
DCUR  0x3c90307f
FLASH 0xff2e0320
DOMC  0x00000000
CERR  0x30080000
DCREV 0x00000024
FREV  0x09010471

**Comment by dglo** [comment]
[jacobsen on 2007-10-15 12:24:18]
Closed per Kael - not repeatable
