### ISSUE TITLE
[jacobsen on 2007-11-26 20:18:36] : Dropped DOM Kills Run

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#645]
It seems that sometimes dropped DOMs can have a catastrophic effect on the run.

E.g., http://warehouse.icecube.wisc.edu/net/user/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751//run.html

[jacobsen@pub3 ~]$ find /net/usr/pdaq/daq-reports/sps/runs/109751* -name '*.log' -exec egrep -H -i 'exception|error' {} \;
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub icecube.daq.domapp.DataCollector-52A ERROR [2007-11-25 15:25:13.869] Timeout on trial 0 getting DOM ID
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:java.nio.channels.ClosedByInterruptException
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub icecube.daq.domapp.DataCollector-52A ERROR [2007-11-25 15:25:13.876] Driver comstat for 52A:
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub icecube.daq.domapp.DataCollector-52A ERROR [2007-11-25 15:25:13.876] FPGA regs for card 5:
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.889] DOM Message exception: sent type = GET_DATA wrapped exception is java.nio.channels.ClosedByInterruptException
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.890]     at icecube.daq.domapp.DOMApp.getData(DOMApp.java:174)
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.891]     at icecube.daq.domapp.DataCollector.runcore(DataCollector.java:863)
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.892]     at icecube.daq.domapp.DataCollector.run(DataCollector.java:686)
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.892] Caused by: java.nio.channels.ClosedByInterruptException
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.893]     at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:212)
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.894]     at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:177)
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.894]     at icecube.daq.domapp.DOMIO.recv(DOMIO.java:72)
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.895]     at icecube.daq.domapp.DOMApp.getData(DOMApp.java:158)
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub STDERR-52A ERROR [2007-11-25 15:25:53.895]     ... 2 more
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-49.log:stringHub icecube.daq.domapp.DataCollector-52A ERROR [2007-11-25 15:25:53.896] Intercepted error in DataCollector runcore: DOM Message exception: sent type = GET_DATA wrapped exception is java.nio.channels.ClosedByInterruptException
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/dash.log:DAQRun [2007-11-25 15:25:53.343084] #16: stringHub#49 inputs: Exception("dom->stringHub#49 sender.NumHitsReceived is not changing") in check() (RunWatchdog.py:80) <- checkValues() (RunWatchdog.py:206) <- checkList() (RunWatchdog.py:192) <- checkComp() (RunWatchdog.py:394)
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/dash.log:DAQRun [2007-11-25 15:25:53.813542] #2: eventBuilder inputs: Exception("globalTrigger->eventBuilder backEnd.NumTriggerRequestsReceived is not changing") in check() (RunWatchdog.py:80) <- checkValues() (RunWatchdog.py:217) <- checkList() (RunWatchdog.py:192) <- checkComp() (RunWatchdog.py:394)
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/dash.log:DAQRun [2007-11-25 15:25:54.015172] Caught error in system, going to ERROR state...
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/dash.log:DAQRun [2007-11-25 15:26:26.788288] Run terminated WITH ERROR.
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-56.log:stringHub icecube.daq.domapp.DataCollector-23A ERROR [2007-11-25 15:24:55.381] Trial 0: Open of 23A failed!
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-56.log:stringHub icecube.daq.domapp.DataCollector-23A ERROR [2007-11-25 15:24:55.411] Driver comstat for 23A:
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-56.log:stringHub icecube.daq.domapp.DataCollector-23A ERROR [2007-11-25 15:24:55.412] FPGA regs for card 2:
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-56.log:stringHub icecube.daq.domapp.DataCollector-23A ERROR [2007-11-25 15:24:55.732] Successful DOMApp retry after initial failure
/net/usr/pdaq/daq-reports/sps/runs/109751_20071125_152626_000062/daqrun109751/stringHub-56.log:java.io.FileNotFoundException: /dev/dhc2w3dA (Resource temporarily unavailable)

**Comment by dglo** [comment]
[kaeld on 2007-12-05 23:46:32]
Add to the list of similarly affected runs 109802 and 109808.  The common theme appears to be a dropped DOM (well, the DOM times out in the GET_DATA call) about 1 min into the run which for some reason takes down the entire system.

**Comment by dglo** [comment]
[kaeld on 2008-04-01 20:47:59]
hard to reproduce

**Comment by dglo** [comment]
[kaeld on 2008-06-02 18:17:17]
this is a real issue - see 111071

**Comment by dglo** [comment]
[kaeld on 2008-06-02 18:21:33]
This may be related to the simple softboot problem (SSP)

**Comment by dglo** [comment]
[kaeld on 2008-06-03 01:34:36]
ok - i know this is happening now that i have re-opened
