### ISSUE TITLE
[jacobsen on 2007-12-20 23:34:10] : splicer - HKN1Splicer dies on Mac laptop

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#704]
Doesn't seem to happen on SPTS64:

jejslab:/mnt/data/pdaq/log/daqrun00508 jacobsen$ exceptions
dash.log:DAQRun [2007-12-20 17:32:56.698227] Run start failed: exceptions.ValueError:Still waiting for 4 components to leave starting (globalTrigger#0, inIceTrigger#0, eventBuilder#0, secondaryBuilders#0)
dash.log:DAQRun [2007-12-20 17:32:59.063268] Run terminated WITH ERROR.
eventBuilder-0.log:eventBuilder STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.205] Exception in thread "HKN1Splicer" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
eventBuilder-0.log:eventBuilder STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.205]      at java.util.ArrayList.RangeCheck(ArrayList.java:546)
eventBuilder-0.log:eventBuilder STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.206]      at java.util.ArrayList.get(ArrayList.java:321)
eventBuilder-0.log:eventBuilder STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.206]      at icecube.daq.hkn1.Node.makeTree(Node.java:145)
eventBuilder-0.log:eventBuilder STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.207]      at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:295)
eventBuilder-0.log:eventBuilder STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.207]      at java.lang.Thread.run(Thread.java:613)
globalTrigger-0.log:globalTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.474] Exception in thread "HKN1Splicer" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
globalTrigger-0.log:globalTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.475]    at java.util.ArrayList.RangeCheck(ArrayList.java:546)
globalTrigger-0.log:globalTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.475]    at java.util.ArrayList.get(ArrayList.java:321)
globalTrigger-0.log:globalTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.476]    at icecube.daq.hkn1.Node.makeTree(Node.java:145)
globalTrigger-0.log:globalTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.479]    at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:295)
globalTrigger-0.log:globalTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.480]    at java.lang.Thread.run(Thread.java:613)
inIceTrigger-0.log:inIceTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.481] Exception in thread "HKN1Splicer" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
inIceTrigger-0.log:inIceTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.481]      at java.util.ArrayList.RangeCheck(ArrayList.java:546)
inIceTrigger-0.log:inIceTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.482]      at java.util.ArrayList.get(ArrayList.java:321)
inIceTrigger-0.log:inIceTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.482]      at icecube.daq.hkn1.Node.makeTree(Node.java:145)
inIceTrigger-0.log:inIceTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.482]      at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:295)
inIceTrigger-0.log:inIceTrigger STDERR-HKN1Splicer ERROR [2007-12-20 17:32:24.486]      at java.lang.Thread.run(Thread.java:613)
secondaryBuilders-0.log:secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.207] Exception in thread "HKN1Splicer" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
secondaryBuilders-0.log:secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.208]    at java.util.ArrayList.RangeCheck(ArrayList.java:546)
secondaryBuilders-0.log:secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.209]    at java.util.ArrayList.get(ArrayList.java:321)
secondaryBuilders-0.log:secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.209]    at icecube.daq.hkn1.Node.makeTree(Node.java:145)
secondaryBuilders-0.log:secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.209]    at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:295)
secondaryBuilders-0.log:secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-20 17:32:26.210]    at java.lang.Thread.run(Thread.java:613)

**Comment by dglo** [comment]
[jacobsen on 2007-12-20 23:34:50]
FYI-stringhub problem on my laptop - i'm on it now

**Comment by dglo** [comment]
[jacobsen on 2007-12-21 00:07:35]
A fresh checkout, and the problem goes away.

**Comment by dglo** [comment]
[jacobsen on 2007-12-21 00:19:02]
Problem was due to forgetting "clean" in my mvn builds -- sorry for the noise.
