### ISSUE TITLE
[ksbeattie on 2008-02-05 23:38:17] : eventBuilder - Illegal subrun errors when calling EBComponent.getEvents()

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#768]
Though I don't think 2318 is strictly related to this issue, but they both were discovered in the same SPS run: 110316.  Where there are many failed calls to get the event count.

I've traced this to the EventBuilderBackEnd.getSubrunTotalEvents() where it fails to find an event count for the given subrun number.  I'm guessing there's a race condition in managing the subrunEventCountMap...

Additional Information: eventBuilder org.apache.xmlrpc.server.XmlRpcStreamServer-XML-RPC-0 ERROR [2008-02-03 15:11:37.952] execute: Error while performing request
org.apache.xmlrpc.common.XmlRpcInvocationException: Failed to invoke method getEvents in class icecube.daq.juggler.component.DAQCompServer: Illegal subrun 2
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:126)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:103)
	at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:43)
	at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:83)
	at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:191)
	at org.apache.xmlrpc.webserver.Connection.run(Connection.java:205)
	at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:63)
Caused by: icecube.daq.juggler.component.DAQCompException: Illegal subrun 2
	at icecube.daq.eventBuilder.EBComponent.getEvents(EBComponent.java:182)
	at icecube.daq.juggler.component.DAQCompServer.getEvents(DAQCompServer.java:599)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:615)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:112)
	... 6 more
Caused by:
icecube.daq.juggler.component.DAQCompException: Illegal subrun 2
	at icecube.daq.eventBuilder.EBComponent.getEvents(EBComponent.java:182)
	at icecube.daq.juggler.component.DAQCompServer.getEvents(DAQCompServer.java:599)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:615)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:112)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:103)
	at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:43)
	at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:83)
	at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:191)
	at org.apache.xmlrpc.webserver.Connection.run(Connection.java:205)
	at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:63)

**Comment by dglo** [comment]
[ksbeattie on 2008-02-15 23:09:55]
This can be reproduced using Dawn anvil script which starts several flasher runs.
