### ISSUE TITLE
[dglo on 2008-03-18 18:40:37] : trigger - cast exceptions with StringTrigger

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#815]
Kael reported the following exception when trying to run the string trigger:

java.lang.ClassCastException: icecube.daq.trigger.impl.HitPayload incompatible with java.lang.Comparable
	at java.util.Collections.sort(Collections.java:136)
	at icecube.daq.trigger.control.SimpleTriggerBag.add(SimpleTriggerBag.java:115)
	at icecube.daq.trigger.control.TriggerHandler.addToTriggerBag(TriggerHandler.java:160)
	at icecube.daq.trigger.algorithm.AbstractTrigger.reportTrigger(AbstractTrigger.java:326)
	at icecube.daq.trigger.algorithm.DefaultStringTrigger.runTrigger(DefaultStringTrigger.java:98)
	at icecube.daq.trigger.control.StringTriggerHandler.process(StringTriggerHandler.java:72)
	at icecube.daq.trigger.control.StringTriggerHandler.receiveByteBuffer(StringTriggerHandler.java:121)

**Comment by dglo** [comment]
[dglo on 2008-03-18 18:42:47]
-- Use SpliceableComparator for sorting non-global trigger bags
Sending        src/main/java/icecube/daq/trigger/control/SimpleTriggerBag.java
Adding         src/main/java/icecube/daq/trigger/control/SpliceableComparator.java
Sending        src/main/java/icecube/daq/trigger/control/TriggerBag.java
Committed revision 2818.
