### ISSUE TITLE
[dglo on 2008-05-01 17:36:53] : dash - DAQStatus.py breaks on some input

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#864]
Mark Krasberg encountered the following error on SPS:

pdaq@sps-expcont[~] 13:29:11 (0)$ DAQStatus.py
CNC localhost:8080
-----------------------
36 unused components
idle
 amandaTrigger
 eventBuilder
 globalTrigger
 iceTopTrigger
 inIceTrigger
 secondaryBuilders
Traceback (most recent call last):
 File "/usr/local/pdaq/pDAQ_current/dash/DAQStatus.py", line 139, in ?
   listTerse(lc)
 File "/usr/local/pdaq/pDAQ_current/dash/DAQStatus.py", line 94, in listTerse
   dumpComp(prevComp, numList, indent)
 File "/usr/local/pdaq/pDAQ_current/dash/DAQStatus.py", line 67, in dumpComp
   while tmpLen > 0 and numStr[tmpLen] != ' ':
IndexError: string index out of range

**Comment by dglo** [comment]
[dglo on 2008-05-01 21:47:51]
-- Fix DAQStatus breakage on certain configurations
Sending        DAQStatus.py
Committed revision 2976.
