### ISSUE TITLE
[jacobsen on 2008-07-23 17:10:50] : DAQStatus.py bug

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#917]
This occurred yesterday - do you want to take this one Dave?

	From: 	  ethan.dicks@usap.gov
	Subject: 	Error with deploying new config *URGENT*
	Date: 	July 22, 2008 9:25:47 AM PDT
	To: 	  john@mail.npxdesigns.com

John,

We just had a power outage here, and part of the collateral damage was to
take down sps-ithub06 (it probably got the "shutdown" message from the UPS,
but as has happened on occasion, it didn't see/react to the "all-clear"
message 30 seconds later, so is now down.

I'm trying to get a 'no-it6' config rolled out, but at step 7 of the
instructions, it says to do 'DAQStatus.py'.  Rather than success, I
got back:

pdaq@sps-expcont[~] 16:05:08 (0)$ DAQStatus.py
CNC localhost:8080
-----------------------
43 unused components
idle
  amandaTrigger
  eventBuilder
  globalTrigger
  iceTopTrigger
  inIceTrigger
  secondaryBuilders
Traceback (most recent call last):
  File "/usr/local/pdaq/pDAQ_current/dash/DAQStatus.py", line 139, in ?
    listTerse(lc)
  File "/usr/local/pdaq/pDAQ_current/dash/DAQStatus.py", line 94, in listTerse
    dumpComp(prevComp, numList, indent)
  File "/usr/local/pdaq/pDAQ_current/dash/DAQStatus.py", line 67, in dumpComp
    while tmpLen > 0 and numStr[tmpLen] != ' ':
IndexError: string index out of range
pdaq@sps-expcont[~] 16:05:18 (1)$

... and I'm not sure how to proceed.

Thanks,

-ethan

-- 
Ethan Dicks, A-333-S     Current South Pole Weather at 22-Jul-2008 at 16:00 Z
South Pole Station
PSC 468 Box 400       Temp  -66.3 F (-54.6 C)   Windchill  -105.7 F (-76.5 C)
APO AP 96598          Wind    14.2 kts Grid 1   Barometer 667.5 mb (11103 ft)

Ethan.Dicks@usap.gov            http://penguincentral.com/penguincentral.html

----- End forwarded message -----

-- 
Ethan Dicks, A-333-S     Current South Pole Weather at 22-Jul-2008 at 16:20 Z
South Pole Station
PSC 468 Box 400       Temp  -65.9 F (-54.4 C)   Windchill  -103.6 F (-75.3 C)
APO AP 96598          Wind    12.8 kts Grid 3   Barometer 667.7 mb (11096 ft)

Ethan.Dicks@usap.gov            http://penguincentral.com/penguincentral.html

**Comment by dglo** [comment]
[dglo on 2008-08-01 21:53:05]
Already fixed in issue 2573
va
