### ISSUE TITLE
[dglo on 2008-10-29 17:24:54] : eventBuilder - throws exception when getting number of events in subrun 1 of run 111868

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#982]
On SPS flasher run 111868, it looks like the eventBuilder was asked for the number of events in subrun 1 (an XML-RPC getEvents() call from DAQRun.rpc_daq_summary_xml()) and EB threw an exception:

Caused by: java.lang.RuntimeException: Illegal subrun 1
        at icecube.daq.eventBuilder.backend.EventBuilderBackEnd.getSubrunTotalEvents(EventBuilderBackEnd.java:628)
        at icecube.daq.eventBuilder.EBComponent.getEvents(EBComponent.java:222)
icecube.daq.juggler.component.DAQCompException: Illegal subrun 1
        at icecube.daq.eventBuilder.EBComponent.getEvents(EBComponent.java:224)
        at icecube.daq.juggler.component.DAQCompServer.getEvents(DAQCompServer.java:589)

**Comment by dglo** [comment]
[dglo on 2012-05-07 18:47:29]
We haven't seen this in the last 3.5 years and the code has changed radically since then, so I'm going to assume this report is no longer relevant.
